import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/screen/Footer";
import Navbar from "@/components/screen/Navbar";
import BottomNav1 from "@/components/ui/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 z-50 w-full px-16">
        <Navbar/>
        </div>
        {children}
        <BottomNav1/>
        <Footer/>
      </body>
    </html>
  );
}
